project/app.py
from flask import Flask


def create_app():

    app = Flask(__name__)

    app.config.from_object("config.Development")

    from .views import view
    app.register_blueprint(view)

    return app

project/main.py
import re
import random
import string
import secrets
from collections.abc import Iterable


def shuffle(array):
    i = 3
    while i > 0:
        random.shuffle(array)
        i -= 1
    return array


def flatt_list(nest_list):
    for i in nest_list:
        if isinstance(i, Iterable) and not isinstance(i, str):
            for j in flatt_list(i):
                yield j
        else:
            yield i
    


class PassGenerator(object):

    def __init__(self):
        self.list = []
        self.password = []

    def password_generator(self):
        letters = string.ascii_letters
        simples = string.punctuation
        digits = string.digits
        keyboard = letters + simples + digits
        self.list = list(keyboard.strip(" "))

        for _ in range(20):
            uniq = random.choice(shuffle(self.list))
            self.password.append(uniq)
        user_pass = "".join(self.password)
        return user_pass

    def token_generator(self):

        samples = list(string.punctuation.strip(" "))
        self.list = list((secrets.token_urlsafe(40)).strip(" "))
        for i in range(5, len(samples), 5):
            shuffle(samples)
            self.list.insert(i, samples[i])
        return "".join(self.list)
    
    def word_generator(self):

        with open('project/static/words.txt', 'r') as text:
            lines = text.readlines()
            for _ in lines:
                # self.list.append(_)
                # print(self.list)
                re.sub(r"[^a-zA-Z0-9]+", " ", _)
                arr = list(_.split(' '))
                self.list.append(arr)
            my_arr = list(flatt_list(self.list))
            for _ in range(15):
                random_word = random.choice(shuffle(my_arr))
                self.password.append(random_word)
            return " ".join(self.password)

            
            


# x = PassGenerator()
# x.word_generator()

project/views.py
from flask import Blueprint, render_template, jsonify
from .main import PassGenerator


view = Blueprint('view', __name__)


@view.route('/')
def home():
    return render_template("index.html")


@view.route('/token')
def token():
    return render_template("token.html")

@view.route('/words')
def words():
    return render_template("words.html")


@view.route('/get_pass')
def get_pass():
    pass_generator = PassGenerator()
    password = pass_generator.password_generator()
    return jsonify(password)


@view.route('/get_token')
def get_token():
    token_generator = PassGenerator()
    token = token_generator.token_generator()
    return jsonify(token)


@view.route('/get_words')
def get_words():
    word_generator = PassGenerator()
    words = word_generator.word_generator()
    return jsonify(words)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="/static/style.css" rel="stylesheet">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body class="d-flex text-center text-white bg-dark">
    <div id="main-div" class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0">Steel Password</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    <a class="nav-link active" aria-current="page" href="{{url_for('view.home')}}">Password</a>
                    <a class="nav-link" href="{{url_for('view.token')}}">Token</a>
                    <a class="nav-link" href="{{url_for('view.words')}}">Text</a>
                </nav>
            </div>
        </header>

        <main class="px-3">
            {% block main %}
            {% endblock main %}
        </main>

        <footer class="mt-auto text-white-50">
            <p>Made with <i class="bi bi-heart-fill"></i>,
                by <a href="https://twitter.com/mdo" class="text-white">MaHDi</a>.
            </p>
        </footer>
    </div>
    <script>
        $(function () {
            $('.nav-masthead').click(function () {
                $('#navigation .active').removeClass('active'); // remove the class from the currently selected
                $(this).addClass('active'); // add the class to the newly clicked link
            });
        });
    </script>
    <script src="/static/script.js"></script>
</body>

</html>

project/templates/index.html
{% extends "base.html" %}

{% block title %}
Password
{% endblock title %}

{% block main %}

<div class="container bg-dark">
    <div class="text">
        Password Generator
    </div>
    <div class="input-data">
        <div id="show" class="display">
            <!-- <input type="text"> -->
            <!-- <span class="far fa-copy" onclick="copy()"></span>
            <span class="fas fa-copy" onclick="copy()"></span> -->
        </div>
        <button id="genPass">Generate Password</button>
        <button id="copy">Copy to clipboard</button>
    </div>
</div>
<!-- <script>

    document.getElementById("copy")
        .onclick = function () {
            let text = document.getElementById("show").value;
            navigator.clipboard.writeText(text)
                .then(() => {
                    alert('Text copied to clipboard');
                })
                .catch(err => {
                    alert('Error in copying text: ', err);
                });
        }
</script> -->

{% endblock main %}

project/templates/token.html
{% extends "base.html" %}

{% block title %}
Token
{% endblock title %}

{% block main %}

<div class="container bg-dark">
    <div class="text">
        Token Generator
    </div>
    <div class="input-data">
        <div id="show" class="display">
            <!-- <input type="text">
            <span class="far fa-copy" onclick="copy()"></span>
            <span class="fas fa-copy" onclick="copy()"></span> -->
        </div>
        <button id="genToken">Generate Token</button>
        <button id="copy">Copy to clipboard</button>
    </div>
</div>
{% endblock main %}

project/templates/words.html
{% extends "base.html" %}

{% block title %}
Words
{% endblock title %}

{% block main %}

<div class="container bg-dark">
    <div class="text">
        Words Generator
    </div>
    <div class="input-data">
        <div id="show" class="display">
            <!-- <input type="text"> -->
            <!-- <span class="far fa-copy" onclick="copy()"></span>
            <span class="fas fa-copy" onclick="copy()"></span> -->
        </div>
        <div>
            <button id="genWords">Generate Words</button>
            <button id="copy">Copy to clipboard</button>
        </div>
    </div>
</div>
<!-- <script>
    $(document).ready(function () {
        $("#copy").click(function () {
            $("input").select();
            alert("Success");
            document.execCommand('copy');
            console.log(
                'Great!!',
                'Content copied to clipboard',
                'success'
            )
        });
    });
</script> -->

{% endblock main %}